version: "3"

services:
  emotion-detection:
    image: emotion-detection:latest
    devices: 
      - /dev/video0:/dev/video0
    environment:
      - PYTHONUNBUFFER=0
      # Uncomment to display video
      # - DISPLAY=$DISPLAY
      - MQTT_HOSTNAME=mosquitto
    volumes:
      # - /tmp/.X11-unix:/tmp/.X11-unix
      - ./emotion-detection-service/app:/app
    working_dir: /app
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./mqtt-service/config:/mosquitto/config
      - ./mqtt-service/data:/mosquitto/data
      - ./mqtt-service/log:/mosquitto/log
    ports:
      - 1883:1883
    expose:
      - 1883

  # backend:
  #   image: nodejs:18.16-alpine